// The domain core is pure: no I/O, no clock, no randomness, no environment.
// "Now" and "a new id" are decided by the caller (the usecase layer) and enter
// as arguments. The guard-core-purity hook enforces this at the tool layer.
import { z } from 'zod';

export const NewNoteSchema = z.object({
  title: z.string().trim().min(1, 'title must not be empty').max(200, 'title too long'),
  tags: z.array(z.string().trim().min(1).max(40)).max(10).default([]),
});
export type NewNote = z.infer<typeof NewNoteSchema>;

export const NoteSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  slug: z.string().min(1),
  tags: z.array(z.string()),
  createdAt: z.string().min(1),
});
export type Note = z.infer<typeof NoteSchema>;

/** Thrown when input fails domain validation. The core owns its own error type. */
export class InvalidNoteError extends Error {
  readonly issues: readonly string[];

  constructor(issues: readonly string[]) {
    super(`invalid note: ${issues.join('; ')}`);
    this.name = 'InvalidNoteError';
    this.issues = issues;
  }
}

export interface NoteIdentity {
  /** Generated by the caller — the core never invents ids. */
  id: string;
  /** ISO-8601 timestamp decided by the caller — the core never reads the clock. */
  createdAt: string;
}

/**
 * The one domain function: validate raw input and construct a Note.
 * Deterministic — identical arguments always yield an identical note.
 */
export function createNote(input: unknown, identity: NoteIdentity): Note {
  const parsed = NewNoteSchema.safeParse(input);
  if (!parsed.success) {
    throw new InvalidNoteError(
      parsed.error.issues.map((issue) => `${issue.path.join('.') || 'input'}: ${issue.message}`),
    );
  }
  const { title, tags } = parsed.data;
  return {
    id: identity.id,
    title,
    slug: slugify(title),
    tags: [...new Set(tags)],
    createdAt: identity.createdAt,
  };
}

/** Lowercased, hyphen-separated, ascii-ish slug. Pure string work. */
export function slugify(title: string): string {
  const slug = title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '') // strip combining marks left by NFKD
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug.length > 0 ? slug : 'note';
}
