import type { ReactNode } from 'react';

// Deliberately unstyled: a starter's frontend is scaffolding, not a product.
// Polish belongs in the mechanism (the shared validation, the boundary hook),
// not in the pixels — replace all of this freely.
export const metadata = {
  title: '__PROJECT_NAME__',
  description: 'Notes — generated by create-agent-rig',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
