/**
 * RP-374 — predecessor upgrade acceptance (RED).
 *
 * `scripts/release-acceptance.mjs` packs and installs only the current
 * candidate; it has no phase that upgrades a rig generated by the real
 * PUBLISHED predecessor to the exact packed candidate. This file pins the
 * failing behaviour for that missing phase — none of the functions below
 * exist in `scripts/release-acceptance.mjs` yet.
 *
 * Assumed production surface (new named exports on `scripts/release-acceptance.mjs`,
 * alongside the existing `formatRigFailure`/`pathWithout`/`treeContains`):
 *
 *   latestReleasedLedgerVersion(ledger: Record<string, string | null>): string
 *     The highest semver key in `ledger` (`templates/release-ledger.json`'s
 *     shape) whose value is non-null — "the ledger's latest released entry".
 *     Throws AcceptanceError('ledger-empty') when every entry is null.
 *
 *   assertVersionAdvances(predecessorVersion: string, candidateVersion: string): void
 *     Throws AcceptanceError('candidate-version-not-advancing') unless
 *     `candidateVersion` is strictly semver-greater than `predecessorVersion`.
 *
 *   acquirePredecessor({ expectedGitHead, expectedShasum, registryView, tarballPath, install }): Promise<T>
 *     Verifies identity BEFORE executing anything: the real sha1 of the file
 *     at `tarballPath` must equal `expectedShasum`, and `registryView.gitHead`
 *     must equal `expectedGitHead`. `expectedShasum`/`expectedGitHead` are the
 *     caller's already-known-good values (in real use: `expectedGitHead` from
 *     the release ledger, `expectedShasum` from `npm view <pkg>@<v> --json`'s
 *     `dist.shasum`; in this test, both are supplied directly — the shasum
 *     computed independently by the test over its own locally-packed stand-in
 *     tarball). Any mismatch or missing field throws an AcceptanceError
 *     ('predecessor-shasum-mismatch' | 'predecessor-githead-mismatch' |
 *     'predecessor-identity-incomplete') WITHOUT ever calling `install` — the
 *     predecessor is never executed on a failed identity check.
 *
 *   assertUserMutationsPreserved({ root, editedPath, editedContent, deletedPath, addedPath, addedContent }): Promise<void>
 *     Reads the three paths under `root` and throws an AcceptanceError
 *     ('user-edit-lost' | 'user-delete-restored' | 'user-add-removed' |
 *     'user-add-corrupted') the moment one does not match what the caller
 *     recorded before upgrading.
 *
 *   acceptPredecessorUpgrade({ scratch, env, predecessorCli, candidateCli, candidateVersion }): Promise<{ manifestVersion: string; secondUpgradeChangedFiles: string[] }>
 *     Generates a rig with `predecessorCli` in a fresh git repo under
 *     `scratch`, edits one rig-managed file, deletes another, adds one
 *     user-owned file, runs `candidateCli upgrade --yes`, asserts
 *     preservation (via `assertUserMutationsPreserved`) and that the written
 *     manifest's `version` advanced to `candidateVersion`, then runs
 *     `candidateCli upgrade --yes` a second time and asserts no file
 *     changed (idempotent).
 */
import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { removeFixture } from '../helpers/remove-fixture.js';

const exec = promisify(execFile);
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const script = path.join(repoRoot, 'scripts', 'release-acceptance.mjs');

// Real, published values for 1.1.1 (journal/ledger evidence) — used only as
// realistic fixture data; the identity checks below verify them against
// injected registry metadata and a locally built stand-in tarball, never
// against the real npm registry.
const REAL_1_1_1_GIT_HEAD = 'd5eac957af3f8208d7ac06491ecf77eb7ec6a7ee';
const REAL_1_1_1_SHASUM = 'dc5830c9ce2b3daf2141790d446c5de3736587b0';

type Module = {
  latestReleasedLedgerVersion?: (ledger: Record<string, string | null>) => string;
  assertVersionAdvances?: (predecessor: string, candidate: string) => void;
  acquirePredecessor?: <T>(options: {
    expectedGitHead: string;
    expectedShasum: string;
    registryView: { gitHead?: string };
    tarballPath: string;
    install: (tarballPath: string) => Promise<T>;
  }) => Promise<T>;
  assertUserMutationsPreserved?: (options: {
    root: string;
    editedPath: string;
    editedContent: string;
    deletedPath: string;
    addedPath: string;
    addedContent: string;
  }) => Promise<void>;
  acceptPredecessorUpgrade?: (options: {
    scratch: string;
    env: NodeJS.ProcessEnv;
    predecessorCli: string;
    candidateCli: string;
    candidateVersion: string;
  }) => Promise<{ manifestVersion: string; secondUpgradeChangedFiles: string[] }>;
};

async function importScript(): Promise<Module> {
  return (await import(pathToFileURL(script).href)) as Module;
}

async function sha1File(file: string): Promise<string> {
  return createHash('sha1')
    .update(await readFile(file))
    .digest('hex');
}

function errorCode(error: unknown): string | undefined {
  return typeof error === 'object' && error !== null && 'code' in error
    ? (error as { code?: string }).code
    : undefined;
}

let scratch: string;

beforeEach(async () => {
  scratch = await mkdtemp(path.join(tmpdir(), 'caf-predecessor-upgrade-'));
});

afterEach(async () => {
  await removeFixture(scratch);
});

describe('release acceptance predecessor ledger lookup', () => {
  it('resolves the highest ledger version that already has a recorded gitHead', async () => {
    const module = await importScript();
    expect(module.latestReleasedLedgerVersion).toBeTypeOf('function');

    const ledger = {
      '0.1.0': null,
      '1.1.0': 'a'.repeat(40),
      '1.1.1': REAL_1_1_1_GIT_HEAD,
    };

    expect(module.latestReleasedLedgerVersion!(ledger)).toBe('1.1.1');
  });

  it('refuses a ledger with no recorded gitHead at all', async () => {
    const module = await importScript();
    expect(module.latestReleasedLedgerVersion).toBeTypeOf('function');

    let caught: unknown;
    try {
      module.latestReleasedLedgerVersion!({ '0.1.0': null });
    } catch (error) {
      caught = error;
    }

    expect(errorCode(caught)).toBe('ledger-empty');
  });
});

describe('release acceptance candidate version advance', () => {
  it('accepts a candidate strictly greater than the predecessor', async () => {
    const module = await importScript();
    expect(module.assertVersionAdvances).toBeTypeOf('function');

    expect(() => module.assertVersionAdvances!('1.1.1', '1.2.0')).not.toThrow();
  });

  it.each([
    ['equal to the predecessor', '1.1.1', '1.1.1'],
    ['lower than the predecessor', '1.1.1', '1.1.0'],
  ])('refuses a candidate version %s', async (_label, predecessor, candidate) => {
    const module = await importScript();
    expect(module.assertVersionAdvances).toBeTypeOf('function');

    let caught: unknown;
    try {
      module.assertVersionAdvances!(predecessor, candidate);
    } catch (error) {
      caught = error;
    }

    expect(errorCode(caught)).toBe('candidate-version-not-advancing');
  });
});

describe('release acceptance predecessor identity', () => {
  async function stubTarball(bytes: string): Promise<string> {
    const file = path.join(scratch, 'stand-in-predecessor.tgz');
    await writeFile(file, bytes);
    return file;
  }

  it('shasum mismatch is refused before the predecessor runs', async () => {
    const module = await importScript();
    expect(module.acquirePredecessor).toBeTypeOf('function');

    const tarballPath = await stubTarball('predecessor bytes that do not match\n');
    let installCalls = 0;

    let caught: unknown;
    try {
      await module.acquirePredecessor!({
        expectedGitHead: REAL_1_1_1_GIT_HEAD,
        expectedShasum: REAL_1_1_1_SHASUM, // deliberately not this tarball's real sha1
        registryView: { gitHead: REAL_1_1_1_GIT_HEAD },
        tarballPath,
        install: async () => {
          installCalls += 1;
          return 'should never run';
        },
      });
    } catch (error) {
      caught = error;
    }

    expect(errorCode(caught)).toBe('predecessor-shasum-mismatch');
    expect(installCalls).toBe(0);
  });

  it('gitHead mismatch is refused before the predecessor runs', async () => {
    const module = await importScript();
    expect(module.acquirePredecessor).toBeTypeOf('function');

    const tarballPath = await stubTarball('predecessor bytes with a correct shasum\n');
    const expectedShasum = await sha1File(tarballPath);
    let installCalls = 0;

    let caught: unknown;
    try {
      await module.acquirePredecessor!({
        expectedGitHead: REAL_1_1_1_GIT_HEAD,
        expectedShasum,
        registryView: { gitHead: '0'.repeat(40) }, // does not match expectedGitHead
        tarballPath,
        install: async () => {
          installCalls += 1;
          return 'should never run';
        },
      });
    } catch (error) {
      caught = error;
    }

    expect(errorCode(caught)).toBe('predecessor-githead-mismatch');
    expect(installCalls).toBe(0);
  });

  it('accepts a tarball whose hash and gitHead both match, and only then runs it', async () => {
    const module = await importScript();
    expect(module.acquirePredecessor).toBeTypeOf('function');

    const tarballPath = await stubTarball('predecessor bytes, verified\n');
    const expectedShasum = await sha1File(tarballPath);
    let installedWith: string | undefined;

    const result = await module.acquirePredecessor!({
      expectedGitHead: REAL_1_1_1_GIT_HEAD,
      expectedShasum,
      registryView: { gitHead: REAL_1_1_1_GIT_HEAD },
      tarballPath,
      install: async (installTarballPath) => {
        installedWith = installTarballPath;
        return 'installed';
      },
    });

    expect(installedWith).toBe(tarballPath);
    expect(result).toBe('installed');
  });
});

describe('release acceptance user-mutation preservation', () => {
  it('detects a lost user edit (mutation-style: the upgrade restored upstream content)', async () => {
    const module = await importScript();
    expect(module.assertUserMutationsPreserved).toBeTypeOf('function');

    const root = scratch;
    await mkdir(path.join(root, '.claude', 'rules'), { recursive: true });
    // Simulates the regression this check exists to catch: upstream content
    // sits where the user's edit should still be.
    await writeFile(path.join(root, '.claude', 'rules', 'workflow.md'), 'upstream content\n');
    await writeFile(path.join(root, 'user-notes.md'), 'kept across upgrade\n');
    // deletedPath intentionally absent — that half is correctly preserved.

    let caught: unknown;
    try {
      await module.assertUserMutationsPreserved!({
        root,
        editedPath: '.claude/rules/workflow.md',
        editedContent: 'upstream content\nuser edit marker\n',
        deletedPath: '.claude/rules/autonomy.md',
        addedPath: 'user-notes.md',
        addedContent: 'kept across upgrade\n',
      });
    } catch (error) {
      caught = error;
    }

    expect(errorCode(caught)).toBe('user-edit-lost');
  });

  it('passes when the edit, the deletion and the addition are all exactly as recorded', async () => {
    const module = await importScript();
    expect(module.assertUserMutationsPreserved).toBeTypeOf('function');

    const root = scratch;
    await mkdir(path.join(root, '.claude', 'rules'), { recursive: true });
    await writeFile(
      path.join(root, '.claude', 'rules', 'workflow.md'),
      'upstream content\nuser edit marker\n',
    );
    await writeFile(path.join(root, 'user-notes.md'), 'kept across upgrade\n');

    await expect(
      module.assertUserMutationsPreserved!({
        root,
        editedPath: '.claude/rules/workflow.md',
        editedContent: 'upstream content\nuser edit marker\n',
        deletedPath: '.claude/rules/autonomy.md',
        addedPath: 'user-notes.md',
        addedContent: 'kept across upgrade\n',
      }),
    ).resolves.toBeUndefined();
  });
});

describe('release acceptance predecessor-to-candidate upgrade', () => {
  async function tarExtract(tarball: string, into: string): Promise<void> {
    await mkdir(into, { recursive: true });
    await exec('tar', ['-xzf', tarball, '-C', into]);
  }

  async function tarCreate(from: string, memberDir: string, out: string): Promise<void> {
    await exec('tar', ['-czf', out, '-C', from, memberDir]);
  }

  /** A locally packed stand-in predecessor: this checkout, repacked under a lower version. */
  async function buildPredecessorTarball(
    candidateTarball: string,
    predecessorVersion: string,
  ): Promise<string> {
    const extracted = path.join(scratch, 'predecessor-src');
    await tarExtract(candidateTarball, extracted);
    const pkgPath = path.join(extracted, 'package', 'package.json');
    const pkg = JSON.parse(await readFile(pkgPath, 'utf8')) as Record<string, unknown>;
    pkg.version = predecessorVersion;
    await writeFile(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
    const out = path.join(scratch, `predecessor-${predecessorVersion}.tgz`);
    await tarCreate(extracted, 'package', out);
    return out;
  }

  async function installCli(tarball: string, prefix: string): Promise<string> {
    await mkdir(prefix, { recursive: true });
    await exec(
      'npm',
      ['install', '--ignore-scripts', '--no-audit', '--no-fund', '--prefix', prefix, tarball],
      { cwd: prefix, maxBuffer: 16 * 1024 * 1024 },
    );
    return path.join(
      prefix,
      'node_modules',
      'create-agent-rig',
      'packages',
      'cli',
      'dist',
      'index.js',
    );
  }

  it('accepts an immutable published predecessor upgrade with an exact packed candidate', async () => {
    const module = await importScript();
    // Fail fast on the missing phase, before any packing/install work runs.
    expect(module.acquirePredecessor).toBeTypeOf('function');
    expect(module.acceptPredecessorUpgrade).toBeTypeOf('function');
    expect(module.assertVersionAdvances).toBeTypeOf('function');

    const packed = JSON.parse(
      (
        await exec('npm', ['pack', '--json', '--pack-destination', scratch], {
          cwd: repoRoot,
          maxBuffer: 16 * 1024 * 1024,
        })
      ).stdout,
    ) as Array<{ filename: string; version: string }>;
    const candidateItem = packed[0]!;
    const candidateTarball = path.join(scratch, candidateItem.filename);
    const candidateVersion = candidateItem.version;

    // The predecessor is this exact codebase, repacked under a lower,
    // clearly-fake version — a stand-in that needs no second real release
    // to exist, and whose identity the test verifies itself rather than
    // trusting the registry.
    const predecessorVersion = '0.0.1';
    const predecessorTarball = await buildPredecessorTarball(candidateTarball, predecessorVersion);
    const expectedShasum = await sha1File(predecessorTarball);
    const expectedGitHead = 'f'.repeat(40);

    module.assertVersionAdvances!(predecessorVersion, candidateVersion);

    const predecessorCli = await module.acquirePredecessor!({
      expectedGitHead,
      expectedShasum,
      registryView: { gitHead: expectedGitHead },
      tarballPath: predecessorTarball,
      install: (tarballPath) => installCli(tarballPath, path.join(scratch, 'predecessor-home')),
    });
    const candidateCli = await installCli(candidateTarball, path.join(scratch, 'candidate-home'));

    const result = await module.acceptPredecessorUpgrade!({
      scratch: path.join(scratch, 'acceptance'),
      env: process.env,
      predecessorCli,
      candidateCli,
      candidateVersion,
    });

    expect(result.manifestVersion).toBe(candidateVersion);
    expect(result.secondUpgradeChangedFiles).toEqual([]);
  }, 120_000);
});
