import { createHash } from 'node:crypto';
import { resolveReadableInside } from '../lib/safe-path.js';
import { readBounded } from './verify.js';
import type { Harness } from './registry.js';

/** Pinned upstream version. Rig never installs it and never runs its launcher. */
export const PROBITY_VERSION = '1.10.1';

/** The file Rig writes when generating a fresh config; never used to look one up. */
export const PROBITY_CONFIG_REL = 'probity.config.mjs';

/** Every config filename Probity itself recognises, in discovery order. */
const CONFIG_CANDIDATES = [
  'probity.config.ts',
  'probity.config.mts',
  'probity.config.js',
  'probity.config.mjs',
] as const;

/**
 * The default config Rig generates. Scoped to the directories a TDD gate
 * actually governs, so an unrelated tree (docs, scripts, templates) never
 * trips it.
 */
export const PROBITY_CONFIG_CONTENTS = `// Generated by create-agent-rig; once you edit this file, Rig treats it as yours.
import { defineConfig, enforceTdd } from '@nizos/probity';

export default defineConfig({
  rules: [
    {
      files: ['src/**', 'lib/**', 'test/**', 'tests/**'],
      rules: [enforceTdd()],
    },
  ],
});
`;

export function probityConfigHash(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

export type ProbityConfigLookup =
  { status: 'absent' } | { status: 'found'; rel: string } | { status: 'unsafe' };

/**
 * Finds any of the four recognised Probity config filenames at the
 * repository root. Read-only — never creates, never deletes.
 */
export async function findProbityConfig(repoDir: string): Promise<ProbityConfigLookup> {
  let unsafe = false;
  for (const rel of CONFIG_CANDIDATES) {
    const resolved = await resolveReadableInside(repoDir, rel, 'file');
    if (resolved.status === 'ok') return { status: 'found', rel };
    if (resolved.status === 'unsafe') unsafe = true;
  }
  return unsafe ? { status: 'unsafe' } : { status: 'absent' };
}

const PROBITY_PACKAGE_JSON_REL = 'node_modules/@nizos/probity/package.json';
const MAX_PROBITY_CHECK_BYTES = 64 * 1024;

/**
 * The installed `@nizos/probity` package version, read only from its own
 * `package.json` — never spawned, never resolved through `require`.
 * `undefined` when the package is not installed or that file is not a
 * readable, parseable `{ version: string }`.
 */
export async function readInstalledProbityVersion(repoDir: string): Promise<string | undefined> {
  const result = await readBounded(repoDir, PROBITY_PACKAGE_JSON_REL, MAX_PROBITY_CHECK_BYTES);
  if (result.status !== 'ok') return undefined;
  let text: string;
  try {
    text = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(result.bytes);
  } catch {
    return undefined;
  }
  try {
    const parsed: unknown = JSON.parse(text);
    return typeof parsed === 'object' &&
      parsed !== null &&
      typeof (parsed as { version?: unknown }).version === 'string'
      ? (parsed as { version: string }).version
      : undefined;
  } catch {
    return undefined;
  }
}

const GATE_MARKER = '.claude/hooks/probity-gate.mjs';
const HARNESS_WIRING_REL: Record<Harness, string> = {
  'claude-code': '.claude/settings.json',
  codex: '.codex/hooks.json',
};

/**
 * Whether this harness's own hook-wiring file carries a `PreToolUse` command
 * naming the Probity gate hook. A bounded, literal substring check against
 * the raw file text — the gate's own slice owns the file's JSON shape, and a
 * diagnostic reader here has no need to parse it to answer this one question.
 */
async function hasGateWiring(repoDir: string, harness: Harness): Promise<boolean> {
  const result = await readBounded(repoDir, HARNESS_WIRING_REL[harness], MAX_PROBITY_CHECK_BYTES);
  if (result.status !== 'ok') return false;
  try {
    return new TextDecoder('utf-8', { fatal: true, ignoreBOM: true })
      .decode(result.bytes)
      .includes(GATE_MARKER);
  } catch {
    return false;
  }
}

export type ProbityInspectionStatus = 'pass' | 'warn' | 'fail';
export type ProbityInspectionReason =
  'config-missing' | 'launcher-missing' | 'version-drift' | 'wiring-missing' | 'wired';
export type ProbityInspection = {
  status: ProbityInspectionStatus;
  reason: ProbityInspectionReason;
};

/**
 * Read-only doctor surface for one declared harness. Checked in order of
 * what Probity itself cannot function without: a config file first (it
 * denies every tool action without one, so this is the one `fail`), then
 * the installed launcher, then the pinned version, then this harness's own
 * gate wiring. Never spawns the Probity launcher.
 */
export async function inspectProbity(
  repoDir: string,
  harness: Harness,
): Promise<ProbityInspection> {
  const config = await findProbityConfig(repoDir);
  if (config.status !== 'found') return { status: 'fail', reason: 'config-missing' };
  const installedVersion = await readInstalledProbityVersion(repoDir);
  if (installedVersion === undefined) return { status: 'warn', reason: 'launcher-missing' };
  if (installedVersion !== PROBITY_VERSION) return { status: 'warn', reason: 'version-drift' };
  if (!(await hasGateWiring(repoDir, harness))) return { status: 'warn', reason: 'wiring-missing' };
  return { status: 'pass', reason: 'wired' };
}
